main: fr.zefire.scandicraft.SPlugin.SPlugin 
name: SPlugin
author: ZeFiRe_
authors: [Pelt10, TheKinrar] 
version: 1.0
commands:
 site:
    description: Afficher le lien du site
    usage: /<command>
    permission: splugin.link.site
 vote:
    description: Afficher le lien pour voter
    usage: /<command>
    permission: splugin.link.vote
 boutique:
    description: Afficher le lien de la boutique
    usage: /<command>
    permission: splugin.link.boutique
 forum:
    description: Afficher le lien du forum
    usage: /<command>
    permission: splugin.link.forum
 ts:
    description: Afficher l'adresse du teamspeak
    usage: /<command>
    permission: splugin.link.ts
 help:
    description: Afficher l'aide
    usage: /<command>
    permission: splugin.essentials.help
 broadcast:
    description: Envoyer un message sur tout le serveur
    usage: /<command>
    permission: splugin.essentials.broadcast
 gm:
    description: Changer votre gamemode
    usage: /<command>
    permission: splugin.essentials.gm
 spawn:
    description: Changer votre gamemode
    usage: /<command>
    permission: splugin.essentials.spawn
permissions:
  splugin.*:
    description: Gives access to all SPlugin commands
    children:
        splugin.essentials.broadcast: true
        splugin.essentials.gm: true
  splugin.essentials.broadcast:
    description: Allow to use broadcast command
    default: op
  splugin.essentials.gm:
    description: Allow to use gm command
    default: op
  splugin.essentials.setspawn:
    description: Allow to use spawn set command
    default: op